# Generated by Django 5.1.7 on 2025-05-25 11:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Жанр',
                'verbose_name_plural': 'Жанры',
            },
        ),
        migrations.CreateModel(
            name='Hall',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='Название')),
                ('number_rows', models.IntegerField(verbose_name='Количество рядов')),
                ('number_places', models.IntegerField(verbose_name='Количество мест в ряду')),
            ],
            options={
                'verbose_name': 'Зал',
                'verbose_name_plural': 'Залы',
            },
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, verbose_name='Название')),
                ('relese_date', models.DateField(verbose_name='Дата выхода')),
                ('description', models.CharField(max_length=600, verbose_name='Описание')),
                ('duration', models.IntegerField(verbose_name='Продолжительность')),
                ('age_limit', models.IntegerField(verbose_name='Возрастное ограничение')),
            ],
            options={
                'verbose_name': 'Кино',
                'verbose_name_plural': 'Кино',
            },
        ),
        migrations.CreateModel(
            name='TicketStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Статус билета',
                'verbose_name_plural': 'Статусы билета',
            },
        ),
        migrations.CreateModel(
            name='MovieGenre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_cinema.genre', verbose_name='Жанр')),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_cinema.movie', verbose_name='Кино')),
            ],
            options={
                'verbose_name': 'Жанр кино',
                'verbose_name_plural': 'Жанр кино',
            },
        ),
        migrations.CreateModel(
            name='Seance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datatime', models.DateTimeField(verbose_name='Дата и время сеанса')),
                ('price', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Стоимость')),
                ('hall', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_cinema.hall', verbose_name='Зал')),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_cinema.movie', verbose_name='Кино')),
            ],
            options={
                'verbose_name': 'Сеанс',
                'verbose_name_plural': 'Сеансы',
            },
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('row', models.IntegerField(verbose_name='Ряд')),
                ('place', models.IntegerField(verbose_name='Место')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Клиент')),
                ('seance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_cinema.seance', verbose_name='Сеанс')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_cinema.ticketstatus', verbose_name='Статус билета')),
            ],
            options={
                'verbose_name': 'Билет',
                'verbose_name_plural': 'Билеты',
            },
        ),
    ]
