# Generated by Django 5.1.7 on 2025-05-25 14:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_cinema', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='seance',
            old_name='datatime',
            new_name='date_and_time',
        ),
    ]
