# Generated by Django 5.1.7 on 2025-05-31 11:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_cinema', '0003_seancestatus_alter_ticket_status_seance_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seance',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_cinema.seancestatus', verbose_name='Статус'),
        ),
    ]
